# Generated by Django 3.2 on 2021-11-05 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label1st',
            fields=[
                ('labelID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('labelName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('dtcreate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dtupdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('personName', models.CharField(default=' ', max_length=20)),
                ('password', models.CharField(default=' ', max_length=2000)),
                ('personImage', models.FileField(upload_to='profile_image')),
                ('dtcreate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dtupdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('taskID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('taskName', models.TextField(blank=True, null=True)),
                ('planStartTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('planFinishTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('actualStartTime', models.DateTimeField(blank=True, null=True)),
                ('actualFinishTime', models.DateTimeField(blank=True, null=True)),
                ('dtcreate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dtupdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('personID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wbsapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='LabelManage',
            fields=[
                ('labelID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('labelName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('dtcreate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dtupdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('labelChildID', models.ManyToManyField(blank=True, default='', to='wbsapp.Label1st')),
                ('taskID', models.ManyToManyField(blank=True, default='', to='wbsapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Label4th',
            fields=[
                ('labelID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('labelName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('dtcreate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dtupdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('taskID', models.ManyToManyField(blank=True, default='', to='wbsapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Label3rd',
            fields=[
                ('labelID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('labelName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('dtcreate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dtupdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('labelChildID', models.ManyToManyField(blank=True, default='', to='wbsapp.Label4th')),
                ('taskID', models.ManyToManyField(blank=True, default='', to='wbsapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Label2nd',
            fields=[
                ('labelID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('labelName', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('dtcreate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dtupdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('labelChildID', models.ManyToManyField(blank=True, default='', to='wbsapp.Label3rd')),
                ('taskID', models.ManyToManyField(blank=True, default='', to='wbsapp.Project')),
            ],
        ),
        migrations.AddField(
            model_name='label1st',
            name='labelChildID',
            field=models.ManyToManyField(blank=True, default='', to='wbsapp.Label2nd'),
        ),
        migrations.AddField(
            model_name='label1st',
            name='taskID',
            field=models.ManyToManyField(blank=True, default='', to='wbsapp.Project'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField()),
                ('dtcreate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dtupdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('taskID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_comments', to='wbsapp.project')),
            ],
        ),
    ]
