# Generated by Django 3.2 on 2021-11-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='labelID',
            field=models.ManyToManyField(to='wbsapp.LabelManage'),
        ),
    ]
