# Generated by Django 3.2 on 2021-11-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wbsapp', '0002_project_labelid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='labelID',
        ),
    ]
